"""Initial migration

Revision ID: 06515517d7aa
Revises: 
Create Date: 2026-07-13 15:16:05.358947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06515517d7aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('certificate_id', sa.String(length=50), nullable=False, comment='Unique public-facing certificate identifier (UUID-based)'),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('certificate_title', sa.String(length=500), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'REVOKED', name='certificatestatus'), server_default='VALID', nullable=False),
    sa.Column('qr_code_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_certificate_id'), 'certificates', ['certificate_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificates_certificate_id'), table_name='certificates')
    op.drop_table('certificates')
    # ### end Alembic commands ###
